In [24]:
import numpy as np
import torch
import warnings
import utils

In [25]:
warnings.filterwarnings('ignore')

In [26]:
columns = utils.loadJsonFile()
model = utils.loadModel()

In [27]:
def predict(country,manufacturer,model_car,body,year,odometer,cyl,engine,fuel,transmission,hp,title_status):
    
    model_car = model_car.lower()
    
    zeros = np.zeros(len(columns))
    title_status_dict = {'missing':0,'lien':1,'salvage':2,'rebuilt':3,'clean':4}
    zeros[0] = year
    zeros[1] = cyl
    zeros[2] = np.sqrt(odometer)
    zeros[3] = title_status_dict[title_status]
    zeros[4] = np.where(transmission=="automatic",1,0)
    zeros[5] = engine
    zeros[6] = hp
    premium_list =  ['gmc','cadillac','audi','bmw','mercedes-benz','infiniti','acura','lexus']
    if manufacturer in premium_list:
        zeros[7] = 1
    else:
        zeros[7] = 0


    manufacturer_idx = np.where(manufacturer == columns)[0][0]
    fuel_idx = np.where(fuel == columns)[0][0]
    type_body_idx = np.where(body == columns)[0][0]
    country_idx = np.where(country == columns)[0][0]
    model_idx = np.where(model_car == columns)[0][0]

    if manufacturer_idx >= 0:
        zeros[manufacturer_idx] = 1


    if fuel_idx >=0:
        zeros[fuel_idx] = 1


    if type_body_idx>=0:
        zeros[type_body_idx] = 1

    if country_idx>=0:
        zeros[country_idx] = 1


    if model_idx>=0:
        zeros[model_idx] = 1

    zeros = np.asarray([zeros])


    zeros = utils.scalerInputs(zeros)
    zeros = torch.from_numpy(zeros).float()
    pred = model(zeros).detach().float()



    return utils.robustTarget(pred)

In [28]:
predict('japan','honda','civic','hatchback',2018,49210,4,2.0,'gas','manual',306,'clean')

array([[33148.66147304]])

In [29]:
predict('usa','chevrolet','silverado','pickup',2020,57020,8,5.3,'gas','automatic',355,'clean')

array([[43571.92560458]])

In [30]:
predict('japan','nissan','sentra','sedan',2011,107070,4,2.0,'gas','automatic',145,'clean')

array([[5834.20829231]])

In [31]:
predict('usa','ford','f-150','pickup',2017,123635,6,3.5,'gas','automatic',282,'clean')

array([[22372.15300524]])

In [32]:
predict('germany','bmw','X7','SUV',2020,30684,6,3.0,'gas','automatic',335,'clean')

array([[61415.38606071]])

In [33]:
predict('germany','audi','Q8','SUV',2023,13253,6,3.0,'gas','automatic',335,'clean')

array([[74243.2786622]])

In [34]:
predict('japan','toyota','RAV4','SUV',2014,127105,4,2.5,'gas','automatic',176,'clean')

array([[14828.99038324]])

In [35]:
predict('usa','gmc','sierra','pickup',2024,2308,8,6.6,'diesel','automatic',401,'clean')

array([[95432.66874695]])

In [36]:
predict('usa','ford','mustang','coupe',2016,20380,8,5.0,'gas','automatic',435,'clean')

array([[29436.77279139]])

In [37]:
predict('germany','bmw','i3','hatchback',2019,22267,0,0,'electric','automatic',168,'clean')

array([[22498.57272589]])

In [38]:
predict('japan','subaru','wrx','sedan',2023,1508,4,2.4,'gas','manual',271,'clean')

array([[39007.65916848]])

In [39]:
predict('japan','toyota','camry','sedan',2015,47295,6,3.5,'gas','automatic',268,'clean')

array([[18362.39652061]])

In [40]:
predict('south korea','kia','stinger','sedan',2019,38750,6,3.3,'gas','automatic',361,'clean')

array([[34922.6540395]])

In [41]:
predict('south korea','hyundai','santa fe','SUV',2017,200589,6,3.3,'gas','automatic',290,'clean')

array([[10988.93965887]])

In [42]:
predict('japan','lexus','ES','sedan',2013,274251,6,3.5,'gas','automatic',268,'clean')

array([[7593.44195271]])

In [43]:
predict('japan','mitsubishi','ES','evolution',2014,137501,4,2.0,'gas','manual',291,'clean')

array([[22287.90961587]])